AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Function
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Role: !GetAtt LambdaRole.Arn
      Handler: handler.function
      Timeout: 120
      CodeUri: ./package
      Environment:
        Variables:
          PROVISIONED_PRODUCT_MAX_TTL_SEC: 86400
      Events:
        CheckProductScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)

  LambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: logs_policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Resource: "*"
        - PolicyName: sc_policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action:
                - "servicecatalog:ScanProvisionedProducts"
                - "servicecatalog:TerminateProvisionedProduct"
              Resource: "*"
      Path: "/"

Outputs:
  FunctionArn: 
    Value: !GetAtt Function.Arn
